import "./mistnosti/klidovka"
import "./mistnosti/koupelna"
import "./mistnosti/kuchyne"
import "./mistnosti/kuchyne"
import "./mistnosti/loznice"
import "./zarizeni/kuchyne/svetlo"
import { RoomModel } from "@senses/core"
